# Generated by Django 2.0.1 on 2019-09-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0004_auto_20190516_0412'),
        ('scheduapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('taskresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_results.TaskResult')),
            ],
            bases=('django_celery_results.taskresult',),
        ),
        migrations.RemoveField(
            model_name='taskresultmodels',
            name='taskresult_ptr',
        ),
        migrations.DeleteModel(
            name='TaskResultModels',
        ),
    ]
